name: "Build ðŸ”¨"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ""
    strategy:
      matrix:
        scheme:
          - "Swiftfin"
          - "Swiftfin tvOS"
          
    runs-on: macos-latest
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
    
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: actions/cache@v2
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
            
      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds
      
      - name: Cache Swift packages
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.scheme }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.scheme }}-spm2-
            
      - name: Cache DerivedData folder
        uses: actions/cache@v2
        with:
          path: "~/Library/Developer/Xcode/DerivedData"
          key: ${{ runner.os }}-${{ matrix.scheme }}-deriveddata
      
      - name: xcodebuild!
        run: |
          xcodebuild build -project "Swiftfin.xcodeproj" \
          -resolvePackageDependencies \
          -scheme "${{ matrix.scheme }}" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO          
      
