name: "Lint ðŸ§¹"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint ðŸ§¹"
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Run SwiftLint
        run: swiftlint --fix
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[ci] SwiftLint"
          reviewers: "acvigue"
