name: "Lint ðŸ§¹"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint ðŸ§¹"
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run Swiftformat
        run: swiftformat . --lint
